/** Short names for the generated contract types. types.ts is generated by `make types`
 *  from vaspfusion/api/schemas.py; never edit it, and add an alias here when a screen needs one. */
import type { components } from './types'

type S = components['schemas']

export type Health = S['Health']
export type Me = S['Me']
export type OfficerOut = S['OfficerOut']
export type Login = S['Login']
export type LoginResult = S['LoginResult']
export type Ok = S['Ok']

export type CaseCreate = S['CaseCreate']
export type CaseSummary = S['CaseSummary']
export type CaseList = S['CaseList']
export type CaseDetail = S['CaseDetail']
export type Hop = S['Hop']
export type Candidate = S['Candidate']
export type EvidenceItem = S['EvidenceItem']
export type TypologyFlag = S['TypologyFlag']
export type FundsSlice = S['FundsSlice']
export type GraphNode = S['GraphNode']
export type GraphEdge = S['GraphEdge']
export type Provenance = S['Provenance']
export type Receipt = S['Receipt']
export type VerifyResult = S['VerifyResult']

export type LabelOut = S['LabelOut']
export type LabelSearch = S['LabelSearch']
export type WalletDetail = S['WalletDetail']

export type Desk = S['Desk']
export type DeskRow = S['DeskRow']
export type VaspDetail = S['VaspDetail']
export type RequestCreate = S['RequestCreate']
export type RequestPatch = S['RequestPatch']
export type RequestDetail = S['RequestDetail']

export type Dashboard = S['Dashboard']
export type ModelInfo = S['ModelInfo']
export type AuditPage = S['AuditPage']

export type Chain = CaseSummary['chain']
export type CaseStatus = CaseSummary['status']
export type Outcome = NonNullable<CaseSummary['outcome']>
export type Tier = LabelOut['tier']
export type Category = LabelOut['category']
export type TypologyCode = TypologyFlag['code']
export type Severity = TypologyFlag['severity']
export type RequestStatus = RequestDetail['status']
export type DataSource = 'mock' | 'live' | 'mixed'
