/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_api_cases_get"];
        put?: never;
        /** Create Case */
        post: operations["create_case_api_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_api_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallets/{chain}/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wallet */
        get: operations["get_wallet_api_wallets__chain___address__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/labels/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Labels */
        get: operations["search_labels_api_labels_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/desk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Desk */
        get: operations["get_desk_api_desk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vasps/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vasp */
        get: operations["get_vasp_api_vasps__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Request */
        post: operations["create_request_api_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Request */
        get: operations["get_request_api_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Request
         * @description Mock: returns the request with the new status applied; nothing persists.
         */
        patch: operations["patch_request_api_requests__request_id__patch"];
        trace?: never;
    };
    "/api/requests/{request_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Request Pdf */
        get: operations["get_request_pdf_api_requests__request_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model
         * @description The deposit-address model's measurements (`make model`). Tron is the model whose
         *     scores the labels carry; `?chain=ethereum` is the explorer-tagged benchmark.
         */
        get: operations["get_model_api_model_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AbstainBar
         * @description One candidate bar: what naming an exchange only at or above it does on the
         *     validation wallets.
         */
        AbstainBar: {
            /** Threshold */
            threshold: number;
            /**
             * Claims Answered
             * @description Claims made through unlabelled wallets
             */
            claims_answered: number;
            /** Claims Wrong */
            claims_wrong: number;
            /**
             * Risk
             * @description claims_wrong / claims_answered
             */
            risk?: number | null;
            /**
             * Risk Upper Bound
             * @description One-sided Clopper-Pearson bound, corrected for the number of bars tried
             */
            risk_upper_bound?: number | null;
            /** Wallets Named */
            wallets_named: number;
            /** Wallets Wrong */
            wallets_wrong: number;
            /** Wallets Abstained */
            wallets_abstained: number;
        };
        /**
         * AbstainInfo
         * @description How the abstain bar was measured (B7): real exchange customers traced with the
         *     derived labels hidden. Not a calibration; read `notes`.
         */
        AbstainInfo: {
            /** Chain */
            chain: string;
            /** Wallets */
            wallets: number;
            /**
             * Claims
             * @description Exchanges named through unlabelled wallets
             */
            claims: number;
            /**
             * Current Threshold
             * @description The bar the cases use
             */
            current_threshold: number;
            /**
             * Measured Threshold
             * @description Lowest bar whose risk stays under target_risk with confidence 1 - delta; null when no bar on the grid does
             */
            measured_threshold?: number | null;
            /** Target Risk */
            target_risk: number;
            /** Delta */
            delta: number;
            /** Bars */
            bars: components["schemas"]["AbstainBar"][];
            /**
             * Risk Coverage
             * @default []
             */
            risk_coverage: components["schemas"]["RiskCoveragePoint"][];
            /**
             * Notes
             * @default []
             */
            notes: string[];
        };
        /** Alert */
        Alert: {
            /** Wallet */
            wallet: string;
            /**
             * Chain
             * @enum {string}
             */
            chain: "tron" | "ethereum" | "bsc" | "polygon" | "arbitrum" | "base" | "optimism" | "avalanche" | "bitcoin" | "solana";
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warn" | "high";
            /** Text */
            text: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Case Id */
            case_id?: string | null;
        };
        /** Candidate */
        Candidate: {
            /** Vasp */
            vasp: string;
            /**
             * Category
             * @enum {string}
             */
            category: "exchange" | "custodial_wallet" | "swap_service" | "sanctioned" | "scam" | "mixer" | "bridge" | "defi" | "entity";
            /**
             * Proximity Rank
             * @description 1 = nearest; hops, share, time
             */
            proximity_rank: number;
            /**
             * Confidence
             * @description Separate from proximity. Label weight x hop decay x share factor. The label weight is the deposit-address model's calibrated probability where confidence_interval is set; otherwise every factor is rule-set
             */
            confidence: number;
            /**
             * Confidence Interval
             * @description Set when the money reached a model-scored deposit address: the model's calibrated range, carried through the same formula. null = rule confidence only
             */
            confidence_interval?: [
                number,
                number
            ] | null;
            /**
             * Direction
             * @description outbound = the wallet's money went there; inbound = it funded the wallet
             * @default outbound
             * @enum {string}
             */
            direction: "outbound" | "inbound";
            /**
             * Hops
             * @description 0 = the wallet itself is a labelled VASP address
             */
            hops: number;
            /** Share Of Funds */
            share_of_funds: number;
            /** Time To Reach S */
            time_to_reach_s?: number | null;
            /**
             * Label Tier
             * @enum {string}
             */
            label_tier: "published_por" | "curated" | "explorer_tag" | "derived";
            /** Deposit Address */
            deposit_address: string;
            /**
             * Path
             * @description Addresses from the suspect to deposit_address
             */
            path: string[];
            /** Evidence */
            evidence: components["schemas"]["EvidenceItem"][];
            /**
             * Counterfactual
             * @description Named candidates only: what happens to this answer when the label on deposit_address (its strongest evidence) is hidden and the wallet is traced again
             * @example Still CoinDCX without the label on TCw8j3…LLcoV5: 58% of the funds reach CoinDCX at TU7BbA…vZbsFs (curated list) in 2 hops, confidence 0.72 (was 0.85).
             */
            counterfactual?: string | null;
            /**
             * Counterfactual Holds
             * @description true: the same VASP is still named without that label. false: it falls under the bar or is not reached. null: not checked (the candidate was not named)
             */
            counterfactual_holds?: boolean | null;
        };
        /** CaseCreate */
        CaseCreate: {
            /** Address */
            address: string;
            /**
             * Chain
             * @description Omit to auto-detect
             */
            chain?: ("tron" | "ethereum" | "bsc" | "polygon" | "arbitrum" | "base" | "optimism" | "avalanche" | "bitcoin" | "solana") | null;
            /** Case Ref */
            case_ref?: string | null;
            /**
             * Complaint No
             * @description 1930 / NCRP complaint number
             */
            complaint_no?: string | null;
            /** Amount Lost Inr */
            amount_lost_inr?: number | null;
            /** Incident Date */
            incident_date?: string | null;
            /**
             * Max Hops
             * @default 3
             */
            max_hops: number;
        };
        /** CaseDetail */
        CaseDetail: {
            /** Id */
            id: string;
            /** Address */
            address: string;
            /**
             * Chain
             * @enum {string}
             */
            chain: "tron" | "ethereum" | "bsc" | "polygon" | "arbitrum" | "base" | "optimism" | "avalanche" | "bitcoin" | "solana";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "failed";
            /** Outcome */
            outcome?: ("ATTRIBUTED" | "INSUFFICIENT_EVIDENCE" | "SANCTIONED_OR_MIXER_REACHED") | null;
            /** Top Vasp */
            top_vasp?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Case Ref */
            case_ref?: string | null;
            /** Complaint No */
            complaint_no?: string | null;
            /** Amount Lost Inr */
            amount_lost_inr?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Demo
             * @default false
             */
            demo: boolean;
            /**
             * Error
             * @description Set when status is 'failed': what went wrong, in plain English
             */
            error?: string | null;
            /**
             * Asset
             * @description The asset that was traced, e.g. USDT
             */
            asset?: string | null;
            /**
             * Total Sent
             * @description What the wallet sent, in `asset`
             */
            total_sent?: number | null;
            /** Total Received */
            total_received?: number | null;
            /**
             * Where Funds Went
             * @description Adds up to the whole of `total_sent`; largest first
             * @default []
             */
            where_funds_went: components["schemas"]["FundsSlice"][];
            /** Hop Rail */
            hop_rail: components["schemas"]["Hop"][];
            graph: components["schemas"]["CaseGraph"];
            /**
             * Candidates
             * @description Sorted by proximity_rank
             */
            candidates: components["schemas"]["Candidate"][];
            /** Typology Flags */
            typology_flags: components["schemas"]["TypologyFlag"][];
            /** Narrative */
            narrative: string;
            /**
             * Abstain Reason
             * @description Set when INSUFFICIENT_EVIDENCE
             */
            abstain_reason?: string | null;
            /**
             * What Would Change
             * @description Evidence that would change an abstain
             * @default []
             */
            what_would_change: string[];
            /**
             * Next Steps
             * @default []
             */
            next_steps: string[];
            provenance: components["schemas"]["Provenance"];
        };
        /** CaseGraph */
        CaseGraph: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /** CaseList */
        CaseList: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["CaseSummary"][];
        };
        /** CaseSummary */
        CaseSummary: {
            /** Id */
            id: string;
            /** Address */
            address: string;
            /**
             * Chain
             * @enum {string}
             */
            chain: "tron" | "ethereum" | "bsc" | "polygon" | "arbitrum" | "base" | "optimism" | "avalanche" | "bitcoin" | "solana";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "failed";
            /** Outcome */
            outcome?: ("ATTRIBUTED" | "INSUFFICIENT_EVIDENCE" | "SANCTIONED_OR_MIXER_REACHED") | null;
            /** Top Vasp */
            top_vasp?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Case Ref */
            case_ref?: string | null;
            /** Complaint No */
            complaint_no?: string | null;
            /** Amount Lost Inr */
            amount_lost_inr?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Demo
             * @default false
             */
            demo: boolean;
            /**
             * Error
             * @description Set when status is 'failed': what went wrong, in plain English
             */
            error?: string | null;
        };
        /** ChainCount */
        ChainCount: {
            /**
             * Chain
             * @enum {string}
             */
            chain: "tron" | "ethereum" | "bsc" | "polygon" | "arbitrum" | "base" | "optimism" | "avalanche" | "bitcoin" | "solana";
            /** Cases */
            cases: number;
        };
        /** Dashboard */
        Dashboard: {
            counts: components["schemas"]["DashboardCounts"];
            /** Outcomes */
            outcomes: {
                [key: string]: number;
            };
            /** Top Vasps */
            top_vasps: components["schemas"]["VaspCount"][];
            /** Chain Mix */
            chain_mix: components["schemas"]["ChainCount"][];
            /** Median Time To Attribution S */
            median_time_to_attribution_s?: number | null;
            /** Recent Alerts */
            recent_alerts: components["schemas"]["Alert"][];
            label_coverage: components["schemas"]["LabelCoverage"];
        };
        /** DashboardCounts */
        DashboardCounts: {
            /** Cases Total */
            cases_total: number;
            /** Open Cases */
            open_cases: number;
            /** Wallets Attributed */
            wallets_attributed: number;
            /** Requests Awaiting Reply */
            requests_awaiting_reply: number;
        };
        /** Desk */
        Desk: {
            /** Follow Ups */
            follow_ups: components["schemas"]["FollowUp"][];
            /** Rows */
            rows: components["schemas"]["DeskRow"][];
        };
        /** DeskRow */
        DeskRow: {
            /** Vasp */
            vasp: string;
            /**
             * Category
             * @enum {string}
             */
            category: "exchange" | "custodial_wallet" | "swap_service" | "sanctioned" | "scam" | "mixer" | "bridge" | "defi" | "entity";
            /** Wallet Count */
            wallet_count: number;
            /** Total Usd */
            total_usd: number;
            /** Case Ids */
            case_ids: string[];
            /** Status */
            status: ("drafted" | "approved" | "sent" | "acknowledged" | "answered" | "freeze_confirmed" | "refused") | "not_requested";
            /** Next Action */
            next_action: string;
            /** Last Request Id */
            last_request_id?: string | null;
        };
        /** EvidenceItem */
        EvidenceItem: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "label" | "path" | "sweep" | "gas_payer" | "model" | "counterfactual";
            /**
             * Text
             * @description Plain English, investigator's words
             */
            text: string;
            /** Tier */
            tier?: ("published_por" | "curated" | "explorer_tag" | "derived") | null;
            /**
             * Tx Hashes
             * @default []
             */
            tx_hashes: string[];
            /**
             * Weight
             * @description Signed contribution (SHAP or rule)
             */
            weight?: number | null;
        };
        /**
         * ExchangeFold
         * @description One row of the leave-one-exchange-out table: the model never saw this exchange.
         */
        ExchangeFold: {
            /** Exchange */
            exchange: string;
            /** N */
            n: number;
            /** N Positive */
            n_positive: number;
            /** Pr Auc */
            pr_auc?: number | null;
            /** Roc Auc */
            roc_auc?: number | null;
            /** Brier */
            brier?: number | null;
            /** Ece */
            ece?: number | null;
            /**
             * Precision
             * @description At probability 0.5
             */
            precision?: number | null;
            /**
             * Recall
             * @description At probability 0.5
             */
            recall?: number | null;
        };
        /** FeatureImportance */
        FeatureImportance: {
            /** Feature */
            feature: string;
            /** Importance */
            importance: number;
        };
        /** FlowSummary */
        FlowSummary: {
            /** Tx Count */
            tx_count: number;
            /** Total Usd */
            total_usd?: number | null;
            /** First Seen */
            first_seen?: string | null;
            /** Last Seen */
            last_seen?: string | null;
            /**
             * Top Counterparties
             * @default []
             */
            top_counterparties: string[];
        };
        /** FollowUp */
        FollowUp: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "reply_overdue" | "freeze_lapsing" | "preservation_closing";
            /** Vasp */
            vasp: string;
            /** Request Id */
            request_id: string;
            /**
             * Due
             * Format: date
             */
            due: string;
            /** Text */
            text: string;
        };
        /**
         * FundsSlice
         * @description One part of the answer to "where did the wallet's money end up?".
         */
        FundsSlice: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "vasp" | "sanctioned" | "mixer" | "bridge" | "other_label" | "hub" | "beyond_hop_limit" | "not_moved" | "not_followed" | "returned";
            /**
             * Name
             * @description The VASP or labelled party, when there is one
             */
            name?: string | null;
            /** Share */
            share: number;
            /** Amount */
            amount: number;
        };
        /** GraphEdge */
        GraphEdge: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Tx Hash */
            tx_hash: string;
            /** Asset */
            asset: string;
            /** Amount */
            amount: number;
            /** Amount Usd */
            amount_usd?: number | null;
            /**
             * Traced Amount
             * @description The part of `amount` that is the suspect wallet's money
             */
            traced_amount?: number | null;
            /**
             * Block Time
             * Format: date-time
             */
            block_time: string;
            /**
             * Direction
             * @default outbound
             * @enum {string}
             */
            direction: "outbound" | "inbound";
        };
        /** GraphNode */
        GraphNode: {
            /**
             * Id
             * @description The address
             */
            id: string;
            /**
             * Chain
             * @enum {string}
             */
            chain: "tron" | "ethereum" | "bsc" | "polygon" | "arbitrum" | "base" | "optimism" | "avalanche" | "bitcoin" | "solana";
            /**
             * Role
             * @enum {string}
             */
            role: "suspect" | "intermediary" | "exchange_hot" | "exchange_deposit" | "exchange" | "custodial_wallet" | "swap_service" | "bridge" | "mixer" | "sanctioned" | "hub" | "unknown";
            /**
             * Hop
             * @description 0 = the suspect wallet
             */
            hop: number;
            label?: components["schemas"]["LabelOut"] | null;
            /**
             * Cluster
             * @description VASP name when collapsible into one node
             */
            cluster?: string | null;
            /**
             * Is Hub
             * @default false
             */
            is_hub: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            /** Label Db */
            label_db: boolean;
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "mock" | "live" | "mixed";
        };
        /**
         * Hop
         * @description One step on the Hop Rail: money moved from `from_address` to `to_address`.
         */
        Hop: {
            /** Index */
            index: number;
            /** From Address */
            from_address: string;
            /** To Address */
            to_address: string;
            /** Tx Hash */
            tx_hash: string;
            /** Asset */
            asset: string;
            /** Amount */
            amount: number;
            /** Amount Usd */
            amount_usd?: number | null;
            /**
             * Traced Amount
             * @description The part of `amount` that is the suspect wallet's money
             */
            traced_amount?: number | null;
            /**
             * Block Time
             * Format: date-time
             */
            block_time: string;
            /**
             * Elapsed S
             * @description Seconds since the previous hop
             */
            elapsed_s?: number | null;
        };
        /** LabelCoverage */
        LabelCoverage: {
            /** Total */
            total: number;
            /** By Category */
            by_category: {
                [key: string]: number;
            };
            /** By Tier */
            by_tier: {
                [key: string]: number;
            };
            /** By Chain */
            by_chain: {
                [key: string]: number;
            };
        };
        /** LabelOut */
        LabelOut: {
            /** Address */
            address: string;
            /**
             * Chain
             * @description Chain slug as stored; 'evm' = any EVM chain
             */
            chain: string;
            /** Entity */
            entity: string;
            /**
             * Category
             * @enum {string}
             */
            category: "exchange" | "custodial_wallet" | "swap_service" | "sanctioned" | "scam" | "mixer" | "bridge" | "defi" | "entity";
            /**
             * Kind
             * @enum {string}
             */
            kind: "hot" | "cold" | "deposit" | "reserve" | "unknown";
            /**
             * Tier
             * @enum {string}
             */
            tier: "published_por" | "curated" | "explorer_tag" | "derived";
            /** Source */
            source: string;
            /** Source Url */
            source_url?: string | null;
            /**
             * Label
             * @description The upstream name tag, verbatim
             */
            label?: string | null;
            /**
             * Confidence
             * @description tier=derived only. With confidence_low/high set: the weight of the exchange wallet's label x the deposit-address model's calibrated probability (B6). Without them: the discovery rules' hand-set confidence, not calibrated
             */
            confidence?: number | null;
            /**
             * Evidence
             * @description tier=derived only: what the sweep and gas-payer rules saw, and what the model said, in plain English
             */
            evidence?: string | null;
            /**
             * Confidence Low
             * @description Model-scored labels only: low end of the calibrated range (Venn-Abers)
             */
            confidence_low?: number | null;
            /** Confidence High */
            confidence_high?: number | null;
            /** @description Labels the deposit-address model scored: its own probability, range and reasons, whether or not the label's confidence is based on it */
            model?: components["schemas"]["ModelScore"] | null;
        };
        /** LabelSearch */
        LabelSearch: {
            /** Query */
            query: string;
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["LabelOut"][];
        };
        /** LetterWallet */
        LetterWallet: {
            /** Address */
            address: string;
            /** Chain */
            chain: string;
            /** Amount Usd */
            amount_usd?: number | null;
            /**
             * Tier
             * @enum {string}
             */
            tier: "published_por" | "curated" | "explorer_tag" | "derived";
            /** First Seen */
            first_seen?: string | null;
            /**
             * Tx Hashes
             * @default []
             */
            tx_hashes: string[];
        };
        /**
         * LookAlikes
         * @description The hard negatives: wallets that are not deposit addresses but forward as much.
         */
        LookAlikes: {
            /** Forwarding At Least */
            forwarding_at_least: number;
            /** Negatives */
            negatives: number;
            /**
             * Flagged
             * @description How many of them the model calls a deposit address
             */
            flagged: number;
            /** False Positive Rate */
            false_positive_rate?: number | null;
        };
        /** ModelInfo */
        ModelInfo: {
            /**
             * Status
             * @enum {string}
             */
            status: "not_measured" | "measured";
            /** Version */
            version?: string | null;
            /** Trained At */
            trained_at?: string | null;
            /**
             * Split
             * @description e.g. 'by exchange and time'
             */
            split?: string | null;
            metrics: components["schemas"]["ModelMetrics"];
            /**
             * Reliability
             * @default []
             */
            reliability: components["schemas"]["ReliabilityBin"][];
            /**
             * Risk Coverage
             * @default []
             */
            risk_coverage: components["schemas"]["RiskCoveragePoint"][];
            /**
             * Feature Importance
             * @default []
             */
            feature_importance: components["schemas"]["FeatureImportance"][];
            /**
             * Leave One Exchange Out
             * @default []
             */
            leave_one_exchange_out: components["schemas"]["ExchangeFold"][];
            look_alikes?: components["schemas"]["LookAlikes"] | null;
            baseline?: components["schemas"]["RuleBaseline"] | null;
            /**
             * Chain
             * @description The chain the model was trained on
             */
            chain?: string | null;
            /**
             * Notes
             * @default []
             */
            notes: string[];
            /** @description How the bar below which no exchange is named was measured on this chain; null when it was not */
            abstain?: components["schemas"]["AbstainInfo"] | null;
        };
        /** ModelMetrics */
        ModelMetrics: {
            /** Pr Auc */
            pr_auc?: number | null;
            /** Ece */
            ece?: number | null;
            /** Brier */
            brier?: number | null;
            /** Accuracy When Answering */
            accuracy_when_answering?: number | null;
            /** Coverage */
            coverage?: number | null;
            /** N Test */
            n_test?: number | null;
        };
        /** ModelReason */
        ModelReason: {
            /**
             * Feature
             * @description The model feature, as a stable key
             */
            feature: string;
            /**
             * Text
             * @description What the address did, in plain English
             */
            text: string;
            /**
             * Weight
             * @description SHAP value in log-odds: above 0 speaks for a deposit address, below 0 against
             */
            weight: number;
        };
        /**
         * ModelScore
         * @description What the deposit-address model said about one address (B6).
         */
        ModelScore: {
            /**
             * P
             * @description Calibrated probability that an address behaving like this is an exchange deposit address
             */
            p: number;
            /**
             * Low
             * @description Venn-Abers range of p
             */
            low: number;
            /** High */
            high: number;
            /**
             * Basis
             * @description model: the label's confidence is the model's value. rule: the model did not raise it, and the discovery rules' confidence is kept
             * @enum {string}
             */
            basis: "model" | "rule";
            /**
             * Scored By
             * @description Which cross-fit model scored it; never one that trained on this address
             */
            scored_by?: string | null;
            /**
             * Reasons
             * @description Strongest reasons, strongest first
             * @default []
             */
            reasons: components["schemas"]["ModelReason"][];
        };
        /** Provenance */
        Provenance: {
            /** Seed */
            seed: number;
            /** Code Version */
            code_version: string;
            /** Label Db Sha256 */
            label_db_sha256?: string | null;
            /** Fetched At */
            fetched_at?: string | null;
            /**
             * Offline Replay
             * @default false
             */
            offline_replay: boolean;
            /**
             * Data Sources
             * @default []
             */
            data_sources: string[];
            /**
             * Notes
             * @description What this run did or could not do, e.g. how many unlabelled wallets the deposit-address model scored
             * @default []
             */
            notes: string[];
        };
        /** ReliabilityBin */
        ReliabilityBin: {
            /** Bin Mid */
            bin_mid: number;
            /** Observed */
            observed: number;
            /** Count */
            count: number;
            /**
             * Predicted
             * @description Mean predicted probability in the bin
             */
            predicted?: number | null;
        };
        /** RequestCreate */
        RequestCreate: {
            /** Vasp */
            vasp: string;
            /** Case Ids */
            case_ids: string[];
            /**
             * Wallets
             * @description Default: every wallet of this VASP in the cases
             */
            wallets?: string[] | null;
            /** Asks */
            asks: ("kyc" | "transactions" | "freeze" | "preservation")[];
            /** Officer */
            officer: string;
        };
        /** RequestDetail */
        RequestDetail: {
            /** Id */
            id: string;
            /** Reference */
            reference: string;
            /** Vasp */
            vasp: string;
            /**
             * Status
             * @enum {string}
             */
            status: "drafted" | "approved" | "sent" | "acknowledged" | "answered" | "freeze_confirmed" | "refused";
            /** Case Ids */
            case_ids: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Due */
            due?: string | null;
            /** Status History */
            status_history: components["schemas"]["StatusEvent"][];
            letter: components["schemas"]["RequestLetter"];
            /** Pdf Url */
            pdf_url: string;
            /**
             * Payload
             * @description SAHYOG JSON payload (docs/sahyog_contract.md, B8)
             */
            payload: {
                [key: string]: unknown;
            };
        };
        /** RequestLetter */
        RequestLetter: {
            /** Reference */
            reference: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** To */
            to: string;
            /** Subject */
            subject: string;
            /** Paragraphs */
            paragraphs: string[];
            /** Wallets */
            wallets: components["schemas"]["LetterWallet"][];
            /** Asks */
            asks: ("kyc" | "transactions" | "freeze" | "preservation")[];
            /** Legal Basis */
            legal_basis: string;
            /** Officer */
            officer: string;
            /**
             * Watermark
             * @description null once approved
             * @default Draft - officer review required
             */
            watermark: string | null;
        };
        /** RequestPatch */
        RequestPatch: {
            /**
             * Status
             * @enum {string}
             */
            status: "drafted" | "approved" | "sent" | "acknowledged" | "answered" | "freeze_confirmed" | "refused";
            /** Note */
            note?: string | null;
        };
        /** RequestSummary */
        RequestSummary: {
            /** Id */
            id: string;
            /** Reference */
            reference: string;
            /** Vasp */
            vasp: string;
            /**
             * Status
             * @enum {string}
             */
            status: "drafted" | "approved" | "sent" | "acknowledged" | "answered" | "freeze_confirmed" | "refused";
            /** Case Ids */
            case_ids: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Due */
            due?: string | null;
        };
        /** RiskCoveragePoint */
        RiskCoveragePoint: {
            /** Coverage */
            coverage: number;
            /** Accuracy */
            accuracy: number;
        };
        /** RiskInfo */
        RiskInfo: {
            /**
             * Score
             * @description null = not yet scored
             */
            score?: number | null;
            /**
             * Reasons
             * @default []
             */
            reasons: string[];
        };
        /**
         * RuleBaseline
         * @description What one rule alone scores on the test addresses: the bar the model must clear.
         */
        RuleBaseline: {
            /** Rule */
            rule: string;
            /** Precision */
            precision?: number | null;
            /** Recall */
            recall?: number | null;
            /** Accuracy */
            accuracy?: number | null;
        };
        /** StatusEvent */
        StatusEvent: {
            /**
             * Status
             * @enum {string}
             */
            status: "drafted" | "approved" | "sent" | "acknowledged" | "answered" | "freeze_confirmed" | "refused";
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Note */
            note?: string | null;
        };
        /** TypologyFlag */
        TypologyFlag: {
            /**
             * Code
             * @description deposit_like is a lead from the deposit-address model on an unlabelled wallet (figures: p, low, high, share, amount); it never changes the outcome
             * @enum {string}
             */
            code: "peel_chain" | "fan_out" | "fan_in" | "rapid_forwarding" | "round_amounts" | "bridge_hop" | "mixer_contact" | "sanctioned_contact" | "deposit_like";
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warn" | "high";
            /** Wallet */
            wallet: string;
            /** Text */
            text: string;
            /**
             * Figures
             * @default {}
             */
            figures: {
                [key: string]: number;
            };
            /**
             * Tx Hashes
             * @default []
             */
            tx_hashes: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VaspCount */
        VaspCount: {
            /** Vasp */
            vasp: string;
            /** Cases */
            cases: number;
            /** Total Usd */
            total_usd: number;
        };
        /** VaspDetail */
        VaspDetail: {
            directory: components["schemas"]["VaspDirectoryEntry"];
            /**
             * Label Counts
             * @description Labelled wallets by chain
             */
            label_counts: {
                [key: string]: number;
            };
            /** Wallets */
            wallets: components["schemas"]["VaspWallet"][];
            /** Requests */
            requests: components["schemas"]["RequestSummary"][];
        };
        /** VaspDirectoryEntry */
        VaspDirectoryEntry: {
            /** Name */
            name: string;
            /** Legal Name */
            legal_name?: string | null;
            /**
             * Fiu Ind Registered
             * @description Only if cited
             */
            fiu_ind_registered?: boolean | null;
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Le Request Channel */
            le_request_channel?: string | null;
            /**
             * Source Urls
             * @default []
             */
            source_urls: string[];
        };
        /** VaspWallet */
        VaspWallet: {
            /** Address */
            address: string;
            /** Chain */
            chain: string;
            /** Case Id */
            case_id?: string | null;
            /**
             * Direction
             * @default outbound
             * @enum {string}
             */
            direction: "outbound" | "inbound";
            /** Amount Usd */
            amount_usd?: number | null;
            /**
             * Tier
             * @enum {string}
             */
            tier: "published_por" | "curated" | "explorer_tag" | "derived";
            /** Confidence */
            confidence?: number | null;
        };
        /** WalletCaseRef */
        WalletCaseRef: {
            /** Case Id */
            case_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "suspect" | "intermediary" | "exchange_hot" | "exchange_deposit" | "exchange" | "custodial_wallet" | "swap_service" | "bridge" | "mixer" | "sanctioned" | "hub" | "unknown";
            /** Hop */
            hop: number;
        };
        /** WalletDetail */
        WalletDetail: {
            /** Address */
            address: string;
            /**
             * Chain
             * @enum {string}
             */
            chain: "tron" | "ethereum" | "bsc" | "polygon" | "arbitrum" | "base" | "optimism" | "avalanche" | "bitcoin" | "solana";
            /** Labels */
            labels: components["schemas"]["LabelOut"][];
            risk: components["schemas"]["RiskInfo"];
            /** Cases */
            cases: components["schemas"]["WalletCaseRef"][];
            inbound?: components["schemas"]["FlowSummary"] | null;
            outbound?: components["schemas"]["FlowSummary"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_cases_api_cases_get: {
        parameters: {
            query?: {
                outcome?: ("ATTRIBUTED" | "INSUFFICIENT_EVIDENCE" | "SANCTIONED_OR_MIXER_REACHED") | null;
                status?: ("queued" | "running" | "done" | "failed") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_case_api_cases_post: {
        parameters: {
            query?: {
                /** @description Trace again even if this wallet already has a finished case */
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_api_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wallet_api_wallets__chain___address__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain: "tron" | "ethereum" | "bsc" | "polygon" | "arbitrum" | "base" | "optimism" | "avalanche" | "bitcoin" | "solana";
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_labels_api_labels_search_get: {
        parameters: {
            query?: {
                q?: string;
                chain?: string | null;
                category?: ("exchange" | "custodial_wallet" | "swap_service" | "sanctioned" | "scam" | "mixer" | "bridge" | "defi" | "entity") | null;
                tier?: ("published_por" | "curated" | "explorer_tag" | "derived") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelSearch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_desk_api_desk_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Desk"];
                };
            };
        };
    };
    get_vasp_api_vasps__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VaspDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_request_api_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_request_api_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_request_api_requests__request_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_request_pdf_api_requests__request_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Until B8 */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
        };
    };
    get_model_api_model_get: {
        parameters: {
            query?: {
                chain?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
