"""The request letter as an A4 PDF (reportlab: pure Python, no system libraries).

The same request always gives the same bytes (`invariant`), so the SHA-256 recorded
when a request is sent identifies the letter that was sent. Pages are left
uncompressed: the file stays small, and the text can be checked by searching it.

A draft says so three ways: a banner on every page, a diagonal watermark, and the
reviewer's notes. Once the request is approved all three are gone.
"""
from __future__ import annotations

from datetime import date, datetime
from io import BytesIO
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import KeepTogether, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from ..explain import fmt
from .routing import day

INK = colors.HexColor("#0E1C27")
SOFT = colors.HexColor("#4A5B69")
RULE = colors.HexColor("#C3CCD4")
DRAFT = colors.HexColor("#A2453B")

BODY = ParagraphStyle("body", fontName="Helvetica", fontSize=10, leading=14, textColor=INK,
                      spaceAfter=7)
BOLD = ParagraphStyle("bold", parent=BODY, fontName="Helvetica-Bold")
RIGHT = ParagraphStyle("right", parent=BODY, alignment=TA_RIGHT, spaceAfter=0)
HEAD = ParagraphStyle("head", parent=BODY, fontName="Helvetica-Bold", fontSize=7.5,
                      leading=9.5, textColor=SOFT, spaceAfter=0)
CELL = ParagraphStyle("cell", parent=BODY, fontSize=8.5, leading=11, spaceAfter=0)
MONO = ParagraphStyle("mono", parent=CELL, fontName="Courier", fontSize=7.5, leading=10)
SMALL = ParagraphStyle("small", parent=BODY, fontSize=8, leading=10.5, textColor=SOFT,
                       spaceAfter=3)
NOTE = ParagraphStyle("note", parent=BODY, fontSize=8.5, leading=11.5, textColor=DRAFT,
                      spaceAfter=3)
SECTION = ParagraphStyle("section", parent=HEAD, fontSize=8.5, leading=11, spaceBefore=8,
                         spaceAfter=4)


def _t(text) -> str:
    """Text for a standard PDF font: characters outside Windows-1252 become '?'."""
    s = "" if text is None else str(text)
    return escape(s.replace("₹", "Rs ").encode("cp1252", "replace").decode("cp1252"))


def _when(value) -> str:
    if not value:
        return "-"
    t = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    return f"{day(t.date())}<br/>{t:%H:%M:%S} UTC"


def _wallet_rows(letter: dict) -> list[list]:
    rows = [[Paragraph(h, HEAD) for h in
             ("#", "WALLET", "AMOUNT TRACED", "EVIDENCE TIER", "CONFIDENCE", "FUNDS FIRST ARRIVED")]]
    for i, w in enumerate(letter["wallets"], 1):
        where = f"{_t(w['chain'].capitalize())} &middot; {_t(w.get('case_ref') or w.get('case_id') or '')}"
        cell = [Paragraph(_t(w["address"]), MONO), Paragraph(where, SMALL)]
        if w.get("paid_into"):
            cell.append(Paragraph("unlabelled; passed everything on to", SMALL))
            cell.append(Paragraph(_t(w["paid_into"]), MONO))
        if w.get("label"):
            cell.append(Paragraph(f"label: {_t(w['label'])}", SMALL))
        amount = fmt.amount(w["amount"], w.get("asset")) if w.get("amount") is not None else "-"
        conf = f"{w['confidence']:.2f}" if w.get("confidence") is not None else "-"
        rows.append([Paragraph(str(i), CELL), cell, Paragraph(_t(amount), CELL),
                     Paragraph(_t(fmt.tier_words(w["tier"])), CELL), Paragraph(conf, CELL),
                     Paragraph(_when(w.get("first_seen")), CELL)])
    return rows


def letter_pdf(request: dict, code_version: str = "") -> bytes:
    """The PDF of a stored request (`RequestDetail`)."""
    letter = request["letter"]
    draft = letter.get("watermark")
    d = date.fromisoformat(str(letter["date"])[:10])
    footer = (f"{letter['reference']}  |  generated by VASP-FUSION"
              + (f" {code_version}" if code_version else "")
              + " from public blockchain records")

    def page(canvas, doc):
        canvas.saveState()
        if draft:
            canvas.setFont("Helvetica-Bold", 38)
            canvas.setFillColor(colors.Color(0.64, 0.27, 0.23, alpha=0.13))
            canvas.translate(A4[0] / 2, A4[1] / 2)
            canvas.rotate(52)
            canvas.drawCentredString(0, 0, draft.upper())
            canvas.rotate(-52)
            canvas.translate(-A4[0] / 2, -A4[1] / 2)
            canvas.setFont("Helvetica-Bold", 9)
            canvas.setFillColor(DRAFT)
            canvas.drawString(18 * mm, A4[1] - 11 * mm, f"{draft.upper()}. NOT SENT.")
        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(SOFT)
        canvas.drawString(18 * mm, 10 * mm, _unescaped(footer))
        canvas.drawRightString(A4[0] - 18 * mm, 10 * mm, f"Page {doc.page}")
        canvas.restoreState()

    story = [
        Paragraph(f"Ref: {_t(letter['reference'])}<br/>Date: {day(d)}", RIGHT),
        Spacer(1, 10),
        Paragraph("To", SMALL),
        Paragraph(_t(letter["to"]), BOLD),
    ]
    if letter.get("channel"):
        story.append(Paragraph(f"Through: {_t(letter['channel'])}", SMALL))
    story += [Spacer(1, 6), Paragraph(f"Subject: {_t(letter['subject'])}", BOLD)]
    for i, p in enumerate(letter["paragraphs"], 1):
        story.append(Paragraph(f"{i}. {_t(p)}", BODY))

    story.append(Paragraph("WALLETS", SECTION))
    table = Table(_wallet_rows(letter), repeatRows=1,
                  colWidths=[6 * mm, 72 * mm, 26 * mm, 26 * mm, 20 * mm, 24 * mm])
    table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LINEBELOW", (0, 0), (-1, 0), 0.8, INK),
        ("LINEBELOW", (0, 1), (-1, -1), 0.4, RULE),
        ("LEFTPADDING", (0, 0), (-1, -1), 2), ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(table)

    story.append(Paragraph("TRANSACTIONS", SECTION))
    for i, w in enumerate(letter["wallets"], 1):
        hashes = w.get("tx_hashes") or []
        story.append(Paragraph(f"Wallet {i}: " + ("" if hashes else "none listed"), SMALL))
        for h in hashes:
            story.append(Paragraph(_t(h), MONO))
    story.append(Spacer(1, 4))

    story.append(Paragraph("LEGAL BASIS", SECTION))
    story.append(Paragraph(_t(letter["legal_basis"]), BODY))
    for c in letter.get("legal_citations", []):
        story.append(Paragraph(
            f"Section {_t(c['section'])}, {_t(c['act'])}: {_t(c['heading'])}. {_t(c['url'])}",
            SMALL))

    story.append(KeepTogether([
        Spacer(1, 22), Paragraph(_t(letter["officer"]), BOLD),
        Paragraph("Investigating officer" if not draft
                  else "Investigating officer (unsigned draft)", SMALL)]))

    if draft and letter.get("review_notes"):
        story.append(Spacer(1, 10))
        story.append(Paragraph("FOR THE REVIEWING OFFICER. NOT PART OF THE REQUEST.",
                               ParagraphStyle("rn", parent=SECTION, textColor=DRAFT)))
        for note in letter["review_notes"]:
            story.append(Paragraph(f"- {_t(note)}", NOTE))

    out = BytesIO()
    doc = SimpleDocTemplate(out, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm,
                            topMargin=18 * mm, bottomMargin=18 * mm, invariant=1,
                            pageCompression=0, title=f"Request {letter['reference']}",
                            author="VASP-FUSION", subject=_unescaped(_t(letter["subject"])))
    doc.build(story, onFirstPage=page, onLaterPages=page)
    return out.getvalue()


def _unescaped(text: str) -> str:
    return text.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")
