import type { RequestLetter } from '../api/models'

/** A CSS string: the reference goes into the @page rule. */
const cssString = (text: string) => `"${text.replace(/[\\"]/g, '\\$&').replace(/[\n\r]/g, ' ')}"`

/** What every printed page carries in its margins: the reference and the page number at the foot,
 *  and on a draft the banner at the head. Chromium prints @page margin boxes. */
export function pageRule(letter: Pick<RequestLetter, 'reference' | 'watermark'>): string {
  const small = 'font-family: "IBM Plex Sans", sans-serif; font-size: 7.5pt; color: #5B5566;'
  const banner = letter.watermark
    ? `@top-left { content: ${cssString(`${letter.watermark.toUpperCase()}. NOT SENT.`)}; font-family: "IBM Plex Sans", sans-serif; font-size: 8pt; font-weight: 600; color: #B3261E; }`
    : ''
  return `@page { size: A4; margin: 17mm 18mm 19mm;
  @bottom-left { content: ${cssString(`${letter.reference}  |  generated by VASP-FUSION from public blockchain records`)}; ${small} }
  @bottom-right { content: "Page " counter(page) " of " counter(pages); ${small} }
  ${banner}
}`
}
